Create models
TekaLishoo/Car_showroom pull request #1
Opened 2022-08-02 11:43 UTC by TekaLishoo

Initial models

2022-08-02 13:08 UTC, tenatarika requested changes
Создай отдельные приложения для Покупателя, шоурума и поставщика

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    wish_body_type = models.ForeignKey('BodyType', related_name='showroom_body_type', on_delete=models.PROTECT)
лучше хранить предпочтения шоурума и кастомера в [jsonfield](https://docs.djangoproject.com/en/4.0/ref/models/fields/#jsonfield)

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    wish_cars = models.ManyToManyField('Car', blank=True)
сделай связь м2м  между машиной и шоурумом], а в промежуточной таблице можно добавить ForeignKey на кастомера и шоурума. С кастомером так же. Также в промежуточной таблице можно хранить скидку если есть.

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    create_time = models.TimeField(auto_now_add=True)
create_time update_time  is_active вынеси в [абстрактуную модель ](https://docs.djangoproject.com/en/4.0/topics/db/models/#abstract-base-classes) и создай папку core в которой будешь хранить эту абстрактную модель

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    balance = models.IntegerField(default=500000)
для баланса лучше использовать библиотеку [Django-money](https://django-money.readthedocs.io/en/latest/)

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    balance = models.IntegerField(default=500000)
Потому что баланс должен быть положительным и тд

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +class Buyer(models.Model):
так же добавь джисон филд с предпочтениями покупателя

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    discount = models.PositiveIntegerField()
добавь валидность от 0 до 100 скидки

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    FUEL_CHOICES = (
вынеси CHOICES в кор

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    is_heated_seats = models.BooleanField()
добавь значения по умолчанию у баллов

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    drive_type = models.ForeignKey('DriveType', related_name='car_drive_type', on_delete=models.PROTECT)
убери эти фк сделай просто чарами

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    amount_showrooms = models.PositiveIntegerField()
это ненужная информация, эта информация достается через простой запрос

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    year_foundation = models.IntegerField(validators=[validators.MinValueValidator(1400),
скобки не по Пеп8 , добавь линтер flake8 или black

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +class CarShowroomCarsPresence(models.Model):
переименуй, название слишком громоздкое(например зачем там два раза Car?)

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    amount = models.PositiveIntegerField()
amount не нужен

2022-08-02 13:08 UTC, tenatarika commented on sell/models.py
> +    price_per_one = models.PositiveIntegerField()
прайс можно просто оставить как price

2022-08-03 09:24 UTC, TekaLishoo commented on sell/models.py
> +    wish_body_type = models.ForeignKey('BodyType', related_name='showroom_body_type', on_delete=models.PROTECT)
Done

2022-08-03 09:59 UTC, tenatarika requested changes
переименуй car_showroom в config(после переименования просто подправь путь до settings.py в manage.py), а все аппки вынеси в папку src и подправь потом названия аппок в настройках они будут называться например src.supplier

2022-08-03 09:59 UTC, tenatarika commented on car_showroom/settings.py
> +    "django.contrib.staticfiles",
отдели пробелом аппки которые ты создала и те которые системные и те которые с либ

2022-08-03 09:59 UTC, tenatarika commented on supplier/models.py
> +    model = models.ForeignKey(
добавь машинам еще пробег и цвет. Цвет вынеси в чойсес

2022-08-03 11:25 UTC, tenatarika approved these changes

2022-08-03 11:25 UTC, tenatarika commented on core/choices.py
> +)
добавь пустую строчку

2022-08-03 11:29 UTC, tenatarika requested changes
добавь gitignore в проект

2022-08-03 11:29 UTC, tenatarika commented on core/wishes.py
> +
core тоже в src перенеси

2022-08-03 11:29 UTC, tenatarika commented on core/wishes.py
> +def default_showroom_wishes():
Зачем тут функцию когда можно просто в переменной хранить?

2022-08-03 11:45 UTC, tenatarika approved these changes

2022-08-03 11:46 UTC, merged